// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1dfL2QRqOhGWU4AfGkyhHZUCQeqOvVQs',
    appId: '1:45671191778:web:2e81e4a21a92a92249fabb',
    messagingSenderId: '45671191778',
    projectId: 'test-daftar-belanja',
    authDomain: 'test-daftar-belanja.firebaseapp.com',
    databaseURL: 'https://test-daftar-belanja-default-rtdb.firebaseio.com',
    storageBucket: 'test-daftar-belanja.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB21Xrx7JOvyNEANVbInCVC8DyG30WMeiM',
    appId: '1:45671191778:android:79ca70afd5f81a5e49fabb',
    messagingSenderId: '45671191778',
    projectId: 'test-daftar-belanja',
    databaseURL: 'https://test-daftar-belanja-default-rtdb.firebaseio.com',
    storageBucket: 'test-daftar-belanja.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxiZJX-c1H9q4nBuYCJyfYvlvwTUtbxRw',
    appId: '1:45671191778:ios:5a62734c4f3228ae49fabb',
    messagingSenderId: '45671191778',
    projectId: 'test-daftar-belanja',
    databaseURL: 'https://test-daftar-belanja-default-rtdb.firebaseio.com',
    storageBucket: 'test-daftar-belanja.appspot.com',
    iosBundleId: 'com.example.daftarBelanja2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxiZJX-c1H9q4nBuYCJyfYvlvwTUtbxRw',
    appId: '1:45671191778:ios:dc22800ab352a78949fabb',
    messagingSenderId: '45671191778',
    projectId: 'test-daftar-belanja',
    databaseURL: 'https://test-daftar-belanja-default-rtdb.firebaseio.com',
    storageBucket: 'test-daftar-belanja.appspot.com',
    iosBundleId: 'com.example.daftarBelanja2.RunnerTests',
  );
}
