// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxqlQf3EOFwFWEN3VYDczd1MIgQUJ6JDA',
    appId: '1:248299501294:web:656460b4d0fe0363b2e5ff',
    messagingSenderId: '248299501294',
    projectId: 'tutorialfirebase-5e507',
    authDomain: 'tutorialfirebase-5e507.firebaseapp.com',
    storageBucket: 'tutorialfirebase-5e507.appspot.com',
    measurementId: 'G-9MFY3EQ1YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtlOSz6V6aXa707hZ5OHonOPcHSs0u4U4',
    appId: '1:248299501294:android:843a02937d7ca90ab2e5ff',
    messagingSenderId: '248299501294',
    projectId: 'tutorialfirebase-5e507',
    storageBucket: 'tutorialfirebase-5e507.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3kWS0FqPEHPIX4P7Vpu11v2gNTQqSgKw',
    appId: '1:248299501294:ios:4d886317fd88f48fb2e5ff',
    messagingSenderId: '248299501294',
    projectId: 'tutorialfirebase-5e507',
    storageBucket: 'tutorialfirebase-5e507.appspot.com',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3kWS0FqPEHPIX4P7Vpu11v2gNTQqSgKw',
    appId: '1:248299501294:ios:77ebc38e1a033607b2e5ff',
    messagingSenderId: '248299501294',
    projectId: 'tutorialfirebase-5e507',
    storageBucket: 'tutorialfirebase-5e507.appspot.com',
    iosBundleId: 'com.example.fasumApp.RunnerTests',
  );
}
