// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNLCRey4zQXVwjo0Uqo_Cy0OFNNKmvsok',
    appId: '1:1024910594246:web:1417ceed68f7f7fde5c7c7',
    messagingSenderId: '1024910594246',
    projectId: 'fasum-app2',
    authDomain: 'fasum-app2.firebaseapp.com',
    databaseURL: 'https://fasum-app2-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI6-mrFI7aAOPhyn-sQ5iI_2cKZkHEY3Q',
    appId: '1:1024910594246:android:f5edc7bc308e3c03e5c7c7',
    messagingSenderId: '1024910594246',
    projectId: 'fasum-app2',
    databaseURL: 'https://fasum-app2-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnC1C8zTC_fY6xG9vtmtpxk5ojfikGsVU',
    appId: '1:1024910594246:ios:56ea00afdf552aa1e5c7c7',
    messagingSenderId: '1024910594246',
    projectId: 'fasum-app2',
    databaseURL: 'https://fasum-app2-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app2.appspot.com',
    iosClientId: '1024910594246-ajqmiql198rolv5k7edreq4bsbk5925v.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnC1C8zTC_fY6xG9vtmtpxk5ojfikGsVU',
    appId: '1:1024910594246:ios:b97d9e3a29f80f02e5c7c7',
    messagingSenderId: '1024910594246',
    projectId: 'fasum-app2',
    databaseURL: 'https://fasum-app2-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app2.appspot.com',
    iosClientId: '1024910594246-8fgct77peteeq6b54vkubb6ql1g64m1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasumApp.RunnerTests',
  );
}
