// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsF9m0NmMNP-YZNyeMX5R9drIZUv8H2xM',
    appId: '1:972184148095:web:ad99261140b68a81a9074a',
    messagingSenderId: '972184148095',
    projectId: 'first-app-66594',
    authDomain: 'first-app-66594.firebaseapp.com',
    databaseURL: 'https://first-app-66594-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-66594.appspot.com',
    measurementId: 'G-RGRT4D2G0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Ui29LCX_eNpg31RzIAQj7EFo1xS6g70',
    appId: '1:972184148095:android:289352aac8a5aad5a9074a',
    messagingSenderId: '972184148095',
    projectId: 'first-app-66594',
    databaseURL: 'https://first-app-66594-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-66594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaOGAfZfAJpWW1qBHt_BmwYWu33IVmAPo',
    appId: '1:972184148095:ios:71b2e50f679deda7a9074a',
    messagingSenderId: '972184148095',
    projectId: 'first-app-66594',
    databaseURL: 'https://first-app-66594-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-66594.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaOGAfZfAJpWW1qBHt_BmwYWu33IVmAPo',
    appId: '1:972184148095:ios:201892ba5f422e26a9074a',
    messagingSenderId: '972184148095',
    projectId: 'first-app-66594',
    databaseURL: 'https://first-app-66594-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-66594.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
